# Site settings
title: Data Science
header-img: img/home-bg.jpg
email: rafehqazi1@gmail.com
description: "Road from a Rookie Starbuckser to Data Scientist."
baseurl: "/data-science"
url: "http://rafeh01.github.io"
twitter_username: RafehQ
github_username:  rafeh01
facebook_username:  ChessTastic

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","vendor"]
