# Site settings
title: Rafeh Qazi
header-img: img/home-bg.jpg
email: rafehqazi1@gmail.com
description: "Coffee and coding enthusiast"
baseurl: "/data-science"
url: ""
twitter_username: RafehQ
github_username:  rafeh01
facebook_username:  ChessTastic

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","vendor"]
